services:
    adh_skeleton.navbar:
        class:  "ADH\\SkeletonBundle\\Service\\Navbar"

    adh_skeleton.form_extension.wysiwyg:
        class:  "ADH\\SkeletonBundle\\Form\\WYSIWYGType"
        tags:
            - { name: "form.type", alias: "wysiwyg" }

    adh_skeleton.twig_extension:
        class:  "ADH\\SkeletonBundle\\Service\\TwigExtension"
        public: false
        tags:
            - { name: "twig.extension" }